[default]
src = 'contracts'
out = 'out'
libs = [
    'lib'
]
remappings = [
    '@contracts/=src/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'ds-test/=lib/ds-test/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    "@forge-std/=lib/forge-std/src/",
]
ffi=true
verbosity=5

# See more config options https://github.com/foundry-rs/foundry/tree/master/config