[default]
out = 'out'                   # output directory conflicts with dapptools
libs = ['lib', "node_modules"]
auto_detect_solc = true
remappings = [
    '@utils/=src/utils/',
    '@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@contracts/=src/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    "@forge-std/=lib/forge-std/src/",
]
ffi = true
verbosity = 5
optimizer = false


[build]
out = 'bout'                   # output directory conflicts with dapptools
libs = ['lib', "node_modules"]
auto_detect_solc = true
remappings = [
    '@utils/=src/utils/',
    '@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@contracts/=src/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    "@forge-std/=lib/forge-std/src/",
]
ffi = true
verbosity = 5
optimizer = false
optimizer_runs = 10
via_ir = true

# See more config options https://github.com/gakonst/foundry/tree/master/config
